### ISSUE TITLE
Does not run on Ubuntu trusty

### ISSUE THREAD

**Issue by probonopd** [andreh11/qrop#1]
Does not run on Ubuntu trusty:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Widgets.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Gui.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Qml.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Qml.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Sql.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Core.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Core.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Core.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libQt5Network.so.5)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libicui18n.so.55)
/run/firejail/appimage/.appimage-10227/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-10227/usr/bin/../lib/libicuuc.so.55)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/1129

**Comment by andreh11** [comment]
Wow, how come you've alreay opened an issue? I guess you have some trackers for AppImage projects on GitHub or Travis... Anyway, thanks. It's my first experience with application deployment, and I'm having a *hard* time figuring out how to properly compile and deploy for Linux, OS X and Windows...

I know that the AppImage doesn't run on Trusty. It's built with Xenial on Travis, because I need the latest version of Qt (5.12) and the PPA I'm using (https://launchpad.net/~beineri) doesn't provide packages for Trusty.

I guess I'll have to make a Docker file... But I've never done that before and I'm still having trouble packaging the application for Windows. And since farmes are more likely to use Windows, I'm going to focus on that first.

**Comment by probonopd** [comment]
Yes, I'm tracking the use of linuxdeployqt and AppImage, to add applications to the catalog at https://appimage.github.io/.

Just out of curiosity, which features of Qt does your app use that are only in 5.12?

**Comment by andreh11** [comment]
I use Qt Quick Controls 2 and Material Design style for it. It's really nice for smartphones, but the controls are a bit too large for desktop use. The recent addition of a "dense" variant for Material style in 5.12 is really what I needed. But sure, using bleeding edge libraries is definitely not good practice...

**Comment by probonopd** [comment]
Please ask [beineri](https://launchpad.net/~beineri) whether he can provide Qt 5.12 for all still-supported versions of Ubuntu, including trusty.
